### PR TITLE
Update data.js

### PR DESCRIPTION
**Pull request by Abhinandan-Sah**
Hello Everyone, those who are facing the problem of validation error. I request to change their data.js file which is inside INIT folder. I have updated the data you can use it or click on this link to get new data [new data.js](https://github.com/Abhinandan-Sah/Horental/blob/main/init/data.js) 

Then, the next step is to again run index.js from INIT so that the new data inside the data.js will get updated in your MongoDB database. I request @apna-college @deltabatch solve this issue in their code.

### CODE REVIEW

**Comment by Sunilkp1998** [comment]
Thanks brother

**Comment by Abhinandan-Sah** [comment]
Welcome bro🙂

**Comment by SHOBHITjain13** [comment]
Nice work bhai

**Review by sarang13579 — APPROVED** [review]

**Comment by heymustafa02** [comment]
Thanks bro

**Pull request closed without merging**
